blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/purpleclay/nsv/discussions
    about: Please ask and answer questions here with other members of the community
