name: nsv
on:
  workflow_dispatch:

jobs:
  nsv:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_NSV }}

      - name: Tag
        uses: dagger/dagger-for-github@v7
        env:
          # skipcq: SCT-A000
          GPG_PRIVATE_KEY: "${{ secrets.GPG_PRIVATE_KEY }}"
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
        with:
          verb: call
          module: github.com/purpleclay/daggerverse/nsv@v0.12.0
          args: --src . tag --show --gpg-private-key env:GPG_PRIVATE_KEY --gpg-passphrase env:GPG_PASSPHRASE
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
